openapi: 3.0.3
info:
  title: Squad data API
  description: API for getting information about squads and its members
  version: 1.0.0
paths:
  /squads:
    get:
      summary: Get all squads 
      description: Returns a list of all squads
      operationId: getSquads
      responses:
        "200":
          description: A list of squads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SquadInfo"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    SquadInfo:
      type: object
      properties:
        name: 
          type: string
        description: 
          type: string
      required:
        - name
    Error:
      type: object 
      properties:
        error:
          type: string
      required:
        - error
